default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  encoding: utf8

development:
  <<: *default
  database: crowdpleaser_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  database: crowdpleaser_test
  host: localhost
  username: postgres
  password: postgres
production:
  <<: *default
  database: crowdpleaser_production
  username: survey
  password: <%= ENV['SURVEY_DATABASE_PASSWORD'] %>
