# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61f43e2825efa299e6529f1d5562190960ca1557071323cc586bc1a59ff102ba8e6dcc6699c22418b590c6ed3641c9e215a87b7c9410a0b924437368984c3272

test:
  secret_key_base: 1d435b0608a28474aeb50b95f6964f19789bdcf868da56769cbeba2e7023017755796d792a4f9f183f136c37cbce27334e8990d95283d9f2561bf65a08a5b77e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
